Lab6/app.py
from flask import Flask
from controllers import *

app = Flask(__name__, template_folder='templates', static_folder='static')

if __name__ == '__main__':
    app.register_blueprint(index_blueprint)
    app.register_blueprint(hello_blueprint)
    app.register_blueprint(olimpiads_blueprint)
    app.register_blueprint(subject_bluprint)

    app.run(debug=True)

Lab6/controllers/__init__.py
from .hello import blueprint as hello_blueprint
from .index import blueprint as index_blueprint
from .olimpiads import blueprint as olimpiads_blueprint
from .subject import blueprint as subject_bluprint

Lab6/controllers/hello.py
from Lab6 import constants
from flask import render_template, request, Blueprint

blueprint = Blueprint('hello', __name__)


@blueprint.route('/hello', methods=['GET'])
def index():
    gender = request.values.get('gender')
    name = request.values.get('username')
    program_id = request.values.get('program')
    subject_id = request.values.getlist('subject[]')
    olimpiads_id = request.values.getlist('olimpiads[]')
    olimpiads_select = [constants.olimpiads[int(i)] for i in olimpiads_id]
    subjects_select = [constants.subjects[int(i)] for i in subject_id]

    html = render_template(
        'hello.jinja2',
        name=name,
        gender=gender,
        program=constants.programs[int(program_id)],
        subjects_select=subjects_select,
        subject_list=constants.subjects,
        olimpiads_select=olimpiads_select
    )
    return html

Lab6/controllers/index.py
from Lab6 import constants
from flask import render_template, Blueprint, request

blueprint = Blueprint('index', __name__)


@blueprint.route('/', methods=['GET'])
def index():
    if request.values.get('clear'):
        gender = None
        name = None
        program_id = None
        subject_id = []
        olimpiads_id = []
    else:
        gender = request.values.get('gender')
        name = request.values.get('username')
        program_id = request.values.get('program')
        subject_id = list(map(int, request.values.getlist('subject')))
        olimpiads_id = list(map(int, request.values.getlist('olimpiads')))

    subjects_selected = [constants.subjects[i] for i in subject_id]
    olimpiads_selected = [constants.olimpiads[i] for i in olimpiads_id]

    html = render_template(
        'index.jinja2',
        len=len,
        program_list=constants.programs,
        subject_list=constants.subjects,
        olimpiad_list=constants.olimpiads,
        name=name,
        gender=gender,
        program=constants.programs[int(program_id)] if program_id else None,
        subjects_selected=subjects_selected,
        olimpiads_selected=olimpiads_selected,
        subject_selected_ids=subject_id,
        olimpiads_selected_ids=olimpiads_id
    )
    return html

Lab6/controllers/olimpiads.py
from Lab6 import constants
from flask import render_template, Blueprint

blueprint = Blueprint('olimpiads', __name__)


@blueprint.route('/olimpiads/<olim>')
def index(olim):
    html = render_template(
        'olimpiads.jinja2',
        olim=olim,
        description=constants.olimpiads_dict[olim]
    )
    return html

Lab6/controllers/subject.py
from Lab6 import constants
from flask import render_template, Blueprint

blueprint = Blueprint('subject', __name__)


@blueprint.route('/subject/<sub>')
def index(sub):
    html = render_template(
        'subject.jinja2',
        sub=sub,
        description=constants.subject_dict[sub]
    )
    return html

Lab6/templates/hello.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
{% if not name %}
    <p>Введите имя пожалуйста!</p>
{% else %}
    <p>Привет {% if gender == 'm' %}студент{% else %}студентка{% endif %}, {{ name }}!</p>
    <p>
        Ваша образовательная программа: {{ program }}
    </p>
    <p>
        {% if subjects_select %}
            Вы изучаете дисциплины:
            {% for sub in subjects_select %}
                <a href={{ url_for('subject.index', sub=sub) }}>{{ sub }}</a>{% if sub != subjects_select[-1] %}, {% endif %}
            {% endfor %}
        {% else %}
            <p>Вы не изучаете никаких дисциплин</p>
        {% endif %}
    </p>
    <p>
        Вы учавствовали в олимпиадах:
        {% for olim in olimpiads_select %}
            <a href={{ url_for('olimpiads.index', olim=olim) }}>{{ olim }}</a>{% if olim != olimpiads_select[-1] %}, {% endif %}
        {% endfor %}
    </p>
{% endif %}
</body>
</html>

Lab6/templates/index.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Приветствие</title>
</head>
<body>
<form action="{{ url_for('index.index') }}" method="get">
    <p>Имя: <input type="text" name="username" value="{% if name %}{{ name }}{% endif %}"></p>
    <p>Пол:<br>
        <input type="radio" name="gender" value="w" {% if gender == 'w' %}checked{% endif %}>Ж<br>
        <input type="radio" name="gender" value="m" {% if gender == 'm' %}checked{% endif %}>M
    </p>
    Образовательная программа:
    <select name="program">
        {% for i in range(len(program_list)) %}
            <option value="{{ i }}"
                    {% if program_list[i] == program %}selected{% endif %}>{{ program_list[i] }}</option>
        {% endfor %}
    </select>
    <p>
        Выберите дисциплины, которые Вы изучаете:<br>
        {% for i in range(len(subject_list)) %}
            <input type="checkbox" name="subject" value="{{ i }}" {% if i in subject_selected_ids %}checked{% endif %}>
            {{ subject_list[i] }}<br>
        {% endfor %}
    </p>
    <p>
        Отметьте олимпиады и конкурсы, в которых Вы участвовали:<br>
        {% for i in range(len(olimpiad_list)) %}
            <input type="checkbox" name="olimpiads" value="{{ i }}"
                   {% if i in olimpiads_selected_ids %}checked{% endif %}>
            {{ olimpiad_list[i] }}<br>
        {% endfor %}
    </p>

    <p>
        <input type="submit" value="Отправить">
        <input type="submit" name="clear" value="Очистить">
    </p>

    {% if name or gender or program or subjects_selected or olimpiads_selected %}
        {% if name %}
            <p>Привет {% if gender == 'm' or gender == None %}студент{% else %}студентка{% endif %}, {{ name }}!</p>
        {% endif %}

        {% if program %}
            <p>Ваша образовательная программа: {{ program }}</p>
        {% endif %}

        {% if subjects_selected %}
            <p>
                Вы изучаете дисциплины:
                {% for sub in subjects_selected %}
                    <a href={{ url_for('subject.index', sub=sub) }}>{{ sub }}</a>
                    {% if sub != subjects_selected[-1] %},{% endif %}
                {% endfor %}
            </p>
        {% endif %}

        {% if olimpiads_selected %}
            <p>
                Вы учавствовали в олимпиадах:
                {% for olim in olimpiads_selected %}
                    <a href={{ url_for('olimpiads.index', olim=olim) }}>{{ olim }}</a>
                    {% if olim != olimpiads_selected[-1] %}, {% endif %}
                {% endfor %}
            </p>
        {% endif %}
    {% endif %}
</form>
</body>
</html>

Lab6/templates/olimpiads.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Олимпиада</title>
</head>
<body>
<img src="/static/img.png">
<p><b>{{ olim }}</b> - это {{ description }}</p>
<p><input name=action onclick="history.back()"
          type=submit value="Вернуться"/>
</p>
</body>
</html>

Lab6/templates/subject.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Дисциплина</title>
</head>
<body>
<img src="/static/img.png">
<p><b>{{ sub }}</b> - это {{ description }}</p>
<p><input name=action onclick="history.back()"
          type=submit value="Вернуться"/>
</p>
</body>
</html>