Lab7/controllers/book.py
from flask import render_template, Blueprint

from .method import Method

blueprint = Blueprint('book', __name__)


@blueprint.route('/book', methods=[Method.GET])
def index():
    html = render_template('book.jinja2')
    return html

Lab7/controllers/index.py
from flask import render_template, request, session, Blueprint

from Lab7.models import ReaderService

from .method import Method

blueprint = Blueprint('index', __name__)
reader_service = ReaderService()


@blueprint.route('/', methods=[Method.GET])
def index():
    if request.values.get('reader'):
        reader_id = int(request.values.get('reader'))
        session['reader_id'] = reader_id
    elif request.values.get('new_reader'):
        new_reader = request.values.get('new_reader')
        session['reader_id'] = reader_service.add_reader(new_reader)
    elif request.values.get('return'):
        book_reader_id = int(request.values.get('return'))
        reader_service.return_book(book_reader_id)
    elif request.values.get('book'):
        book_id = int(request.values.get('book'))
        reader_service.borrow_book(book_id, session['reader_id'])
    else:
        session['reader_id'] = 1

    df_reader = reader_service.get_readers()
    df_book_reader = reader_service.get_reader_books(session['reader_id'])

    html = render_template(
        'index.jinja2',
        reader_id=session['reader_id'],
        combo_box=df_reader,
        book_reader=df_book_reader,
        len=len
    )
    return html

Lab7/controllers/new_reader.py
from flask import render_template, Blueprint

from .method import Method

blueprint = Blueprint('new_reader', __name__)


@blueprint.route('/new_reader', methods=[Method.GET])
def index():
    html = render_template('new_reader.jinja2')
    return html

Lab7/controllers/search.py
from flask import render_template, request, Blueprint

from Lab7.models import SearchService

from .method import Method

blueprint = Blueprint('search', __name__)
search_service = SearchService()


@blueprint.route('/search', methods=[Method.GET, Method.POST])
def index():
    authors = search_service.get_authors()
    publishers = search_service.get_publishers()
    genres = search_service.get_genres()

    if request.form.get('clear'):
        selected_genres = []
        selected_publishers = []
        selected_authors = []
    else:
        selected_genres = list(map(int, request.form.getlist('genre_id')))
        selected_publishers = list(map(int, request.form.getlist('publisher_id')))
        selected_authors = list(map(int, request.form.getlist('author_id')))

    cards = search_service.get_cards(selected_genres, selected_publishers, selected_authors)

    html = render_template(
        'search.jinja2',
        authors=authors,
        publishers=publishers,
        genres=genres,
        cards=cards,
        selected_authors=selected_authors,
        selected_publishers=selected_publishers,
        selected_genres=selected_genres,
        len=len
    )
    return html

Lab7/controllers/statistics.py
from flask import render_template, Blueprint

from .method import Method

blueprint = Blueprint('statistics', __name__)


@blueprint.route('/statistics', methods=[Method.GET])
def index():
    html = render_template('statistics.jinja2')
    return html

Lab7/templates/book.jinja2
{% from 'macros.jinja2' import render_menu %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
    <title>Книги</title>
</head>
<body>
{{ render_menu(1) }}
Книги!
</body>
</html>

Lab7/templates/index.jinja2
{% from 'macros.jinja2' import render_menu, render_readers, render_table %}

<!DOCTYPE HTML>
<html lang="ru">
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/table.css') }}"/>
    <title>Карточка читателя</title>
</head>
<body>
{{ render_menu(0) }}
<div class="block">
    <form action="" method="get">
        {{ render_readers(combo_box, reader_id, len) }}
        <input type="submit" value="Найти">
    </form>
    
    <form action="{{ url_for('new_reader.index') }}" method="get">
        <input type="submit" value="Новый читатель">
    </form>

    {{ render_table('Карточка', ('Название', 'Авторы', 'Дата выдачи', 'Дата возврата'), book_reader, 'book_reader_id', len) }}

    <form action="{{ url_for('search.index') }}" method="get">
        <input type="submit" value="Взять книгу">
    </form>
</div>
</body>
</html>

Lab7/templates/macros.jinja2
<!DOCTYPE html>
{% macro render_table(table_name, header, data, id, len) %}
    <p>
        <b>{{ table_name }}</b>
    </p>
    <table>
        <tr style="background-color: rgb(242, 242, 242);">
            {% for name in header %}
                <th>{{ name }}</th>
            {% endfor %}
        </tr>
        <tbody>

        {% for record in data %}
            <tr>
                {% for i in range(len(header)) %}
                    <td>
                        {% if header[i] == 'Дата возврата' and not record[i] %}
                            <form action="" method="get">
                                <input type="hidden" name="return" value="{{ record[4] }}">
                                <input type="submit" value="Сдать">
                            </form>
                        {% else %}
                            {{ record[i] }}
                        {% endif %}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endmacro %}

{% macro render_readers(readers, reader_id, len) %}
    <label>
        Читатель:
        <select name="reader" required>
            {% for reader in readers %}
                <option value="{{ reader[0] }}"
                        {% if reader[0] == reader_id %}selected{% endif %}>{{ reader[1] }}</option>
            {% endfor %}
        </select>
    </label>
{% endmacro %}

{% macro render_filters(name, names, filters, selected_filters, len) %}
    <fieldset>
        <legend>{{ name }}</legend>
        {% for filter in filters %}
            <div class="checkbox-wrapper">
                <input type="checkbox"
                       name="{{ names[0] }}"
                       value="{{ filter[0] }}"
                       {% if filter[0] in selected_filters %}checked{% endif %}>
                <label>
                    {{ filter[1] }} ({{ filter[2] }})
                </label>
            </div>
        {% endfor %}
    </fieldset>
{% endmacro %}

{% macro render_cards(cards, names, len) %}
    {% for card in cards %}
        <div class="card">
            {% for i in range(len(names)) %}
                <p>{{ names[i] }}: <b>{{ card[i] }}</b></p>
            {% endfor %}
            <div class="button-wrapper">
                <form action="{{ url_for('index.index') }}" method="get">
                    <input type="submit"
                           value="Выбрать"
                           {% if card[5] == 0 %}disabled{% endif %}>
                    <label>
                        <input type="hidden" name="book" value="{{ card[6] }}">
                    </label>
                </form>
            </div>
        </div>
    {% endfor %}
{% endmacro %}

{% macro render_selected_filters(filters, selections, name, len) %}
    {% if selections %}
        <p>{{ name }}:
            {% for filter in filters %}
                {% if filter[0] in selections %}
                    {{ filter[1] }}{% if filter[0] != selections[-1] %},{% else %}.{% endif %}&nbsp;
                {% endif %}
            {% endfor %}
        </p>
    {% endif %}
{% endmacro %}

{% macro render_menu(selected) %}
    <div class="menu">
        <ul>
            <li {% if selected == 0 %}class="active"{% endif %}>
                <a href={{ url_for('index.index') }}>Читатель</a>
            </li>
            <li {% if selected == 1 %}class="active"{% endif %}>
                <a href={{ url_for('book.index') }}>Книги</a>
            </li>
            <li {% if selected == 2 %}class="active"{% endif %}>
                <a href={{ url_for('statistics.index') }}>Статистика</a>
            </li>
        </ul>
    </div>
{% endmacro %}

Lab7/templates/new_reader.jinja2
{% import "macros.jinja2" as macros %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
    <title>Новый читатель</title>
</head>
<body>
<div class="menu">
    <ul>
        <li class="active">
            <a href="/">Новый читатель</a>
        </li>
    </ul>
</div>
<div class=block>
    <form action="{{ url_for('index.index') }}" method="get">
        <label>
            Имя читателя:
            <input type="text" name="new_reader" required>
        </label>
        <input type="submit" value="Добавить читателя">
        <input type="button" onclick="window.location='{{ url_for('index.index') }}'" value="Отменить">
    </form>
</div>
</body>
</html>

Lab7/templates/search.jinja2
{% from 'macros.jinja2' import render_filters, render_cards, render_selected_filters %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Поиск</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/search.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
</head>
<body>
<div class="menu">
    <ul>
        <li class="active">
            <a href="/">Поиск книг</a>
        </li>
    </ul>
</div>
<div class="content">
    <div class="lists">
        <form action="" method="post">
            {{ render_filters('Жанры', ('genre_id', 'genre_name', 'count'), genres, selected_genres, len) }}
            {{ render_filters('Авторы', ('author_id', 'author_name', 'count'), authors, selected_authors, len) }}
            {{ render_filters('Издательства', ('publisher_id', 'publisher_name', 'count'), publishers, selected_publishers, len) }}
            <br>
            <input type="submit" value="Найти">
            <input type="submit" name="clear" value="Очистить">
        </form>
    </div>
    <div class="result">
        <a class="search-menu" type="button" href="{{ url_for('index.index') }}">Не выбирать книгу</a>
        <div class="search-menu chosen">
            {{ render_selected_filters(genres, selected_genres, 'Жанры', len) }}
            {{ render_selected_filters(authors, selected_authors, 'Авторы', len) }}
            {{ render_selected_filters(publishers, selected_publishers, 'Издательства', len) }}
        </div>
        <div class="cards">
            {{ render_cards(cards, ('Название', 'Авторы', 'Жанр', 'Издательство', 'Год издания', 'Количество', 'ID'), len) }}
        </div>
    </div>
</div>
</body>
</html>

Lab7/templates/statistics.jinja2
{% from 'macros.jinja2' import render_menu %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Статистика</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
</head>
<body>
{{ render_menu(2) }}
<p>Статистика!</p>
</body>
</html>